/* GENERATED FILE. Do not hand-edit.
 * Produced by scripts/build_strings.py from strings.en.json + strings.zh.json.
 * Rerun build_strings.py (after zh_copy.py for any new keys) to regenerate. */
window.STRINGS = {
  "en": {
    "nav.home": "Home",
    "nav.service": "Our Service",
    "nav.shop": "Shop",
    "nav.team": "Our Team",
    "nav.corporate": "Corporate Event",
    "nav.media": "Media",
    "nav.contact": "Contact Us",
    "nav.menu_aria": "Menu",
    "nav.lang_aria": "Language",
    "cta.book": "Book a court",
    "cta.classes": "See classes",
    "hero.eyebrow": "Opening November 2026",
    "hero.lead": "Volleyball, basketball, pickleball, badminton. One roof, Hong Kong.",
    "pillar.venue": "Venue",
    "pillar.venue.desc": "Courts by the hour. Volleyball, basketball, pickleball, badminton.",
    "pillar.class": "Class",
    "pillar.class.desc": "Sport classes, S&C sessions and certificate courses.",
    "pillar.pt": "Personal training",
    "pillar.pt.desc": "Pick your Just Performance coach, then pick a time. 1:1 to 1:8.",
    "pillar.eyebrow": "Three ways to book",
    "pillar.title": "What you can book",
    "price.from": "from HK$ TBC",
    "price.fromTemplate": "from {p}",
    "intro.eyebrow": "Sporting Hub Hong Kong",
    "intro.title": "A proper indoor venue, built for the sports Hong Kong actually plays.",
    "intro.body1": "Four courts across two halls, a strength and conditioning floor run by Just Performance, a recovery zone, changing rooms and lockers, and a small shop and supper corner.",
    "intro.body2": "Open to everyone. Book by the hour, join a class, or bring the whole office.",
    "intro.link": "See the venue",
    "spaces.eyebrow": "The venue",
    "spaces.title": "Eight spaces, one address.",
    "spaces.volleyball": "Volleyball court",
    "spaces.basketball": "Basketball court",
    "spaces.pickleball": "Pickleball court",
    "spaces.badminton": "Badminton court",
    "spaces.sc": "Strength and conditioning floor",
    "spaces.lounge": "Lounge",
    "spaces.retail": "Shop",
    "spaces.recovery": "Recovery zone",
    "jp.eyebrow": "Personal training",
    "jp.title": "Just Performance, in the building.",
    "jp.body": "Strength and conditioning by Just Performance, based here at Sporting Hub Hong Kong. Choose your coach first, then a time that suits you. Sessions run 1:1 to 1:Team, up to 16.",
    "jp.cta": "Choose a coach",
    "jp.groupSize": "1:1 to 1:8",
    "jp.book": "Book",
    "jp.coach1.name": "Head coach",
    "jp.coach1.chip1": "Strength",
    "jp.coach1.chip2": "Conditioning",
    "jp.coach2.name": "S&C coach",
    "jp.coach2.chip1": "Mobility",
    "jp.coach2.chip2": "Rehab",
    "jp.coach3.name": "Volleyball coach",
    "jp.coach3.chip1": "Volleyball",
    "jp.coach3.chip2": "Jump training",
    "jp.tbcBio": "Name and bio to confirm",
    "corp.eyebrow": "Corporate events",
    "corp.title": "Team days, tournaments, private hire.",
    "corp.body": "The whole venue or a single court. Tell us the date and headcount and we will come back with a quote.",
    "corp.ctaPrimary": "Enquire",
    "corp.wa": "WhatsApp",
    "shop.eyebrow": "Shop",
    "shop.title": "Caps, hoodies, tees, totes.",
    "shop.link": "Visit the shop",
    "shop.tbcName": "Store name to confirm",
    "band.title": "Book a court",
    "band.sub": "Pick the sport, then the hour.",
    "band.sport.vb": "Volleyball",
    "band.sport.bb": "Basketball",
    "band.sport.pb": "Pickleball",
    "band.sport.bd": "Badminton",
    "band.classes": "Classes",
    "band.pt": "Personal training",
    "find.eyebrow": "Find us",
    "find.title": "In Hong Kong. Address to follow.",
    "find.addressLabel": "Address",
    "find.addressValue": "To confirm",
    "find.hoursLabel": "Opening hours",
    "find.hoursValue": "To confirm",
    "find.mtrLabel": "MTR",
    "find.mtrValue": "To confirm",
    "find.waLabel": "WhatsApp",
    "find.waValue": "To confirm",
    "find.emailLabel": "Email",
    "find.emailValue": "To confirm",
    "find.waBtn": "WhatsApp us",
    "find.directionsBtn": "Get directions",
    "find.mapCaption": "Map embeds once the address is confirmed",
    "footer.blurb": "An indoor sports venue in Hong Kong. Courts, classes, coaching and kit.",
    "footer.bookCol": "Book",
    "footer.venueCol": "Venue",
    "footer.companyCol": "Company",
    "footer.linkVenue": "Venue",
    "footer.linkClass": "Class",
    "footer.linkPt": "Personal training",
    "footer.linkService": "Our Service",
    "footer.linkTeam": "Our Team",
    "footer.linkCorporate": "Corporate Event",
    "footer.linkMedia": "Media",
    "footer.linkShop": "Shop",
    "footer.linkContact": "Contact Us",
    "footer.linkPrivacy": "Privacy",
    "footer.bottomName": "Sporting Hub Hong Kong",
    "wa.ariaLabel": "Message us on WhatsApp",
    "wa.tbcNumber": "Number to confirm",
    "bk.wa_aria": "Ask a question on WhatsApp",
    "bk.back": "Back",
    "bk.next": "Next",
    "bk.pay": "Confirm and pay",
    "bk.s1_h": "Which sport?",
    "bk.s1_sub": "Pick your sport, then how long you need. Maximum 2 hours per HKID.",
    "bk.s1c_h": "What kind of class?",
    "bk.s1c_sub": "Sport, strength and conditioning, and certificates share one calendar.",
    "bk.s5_h": "Choose your coach",
    "bk.s5_sub": "Personal training by Just Performance. Pick the coach, then their calendar.",
    "bk.s5b_h": "Which ratio?",
    "bk.s5b_sub": "Coach to athlete. Each ratio is priced differently.",
    "bk.s3_h": "Pick a session",
    "bk.s2_h": "Pick a date and time",
    "bk.s2_note": "Pick one time slot per hour booked. They do not have to run back to back.",
    "bk.s6_h": "Your details",
    "bk.s6_sub": "We send the confirmation here.",
    "bk.s6_warn": "Fill in your name, email and phone, and accept the waiver.",
    "bk.f_first": "First name",
    "bk.f_last": "Last name",
    "bk.f_email": "Email",
    "bk.f_phone": "Phone",
    "bk.f_notes": "Anything we should know",
    "bk.f_notes_ph": "Injuries, equipment, arrival time",
    "bk.c_waiv": "I accept the terms and conditions and the 48 hour cancellation policy.",
    "bk.c_mkt": "Send me occasional news about classes and events.",
    "bk.s7_h": "Check and confirm",
    "bk.s7_sub": "Nothing is charged in this prototype.",
    "bk.s8_h": "You are booked",
    "bk.s8_sub": "A confirmation is on its way to your email.",
    "bk.s8_home": "Back to home",
    "bk.s8_again": "Book something else",
    "bk.sum_h": "Your booking",
    "bk.sum_total": "Total",
    "bk.policy": "Free cancellation up to 48 hours before the session. Inside 48 hours the booking is non-refundable.",
    "bk.cr_l": "Backend change request",
    "bk.cr_cat": "This category step sits ahead of the standard Bliss flow. Confirm with Edward that it can be added without affecting other Bliss clients.",
    "bk.cr_coach": "Bliss goes store, then date, then time, then item. This picks the coach first. Confirm with Edward. Fallback: date first with a coach filter.",
    "bk.cr_pay": "Payment runs on the existing Bliss checkout and payment channel. Nothing new is built here.",
    "bk.st_court": "Court",
    "bk.st_cat": "Class type",
    "bk.st_coach": "Coach",
    "bk.st_size": "Ratio",
    "bk.st_when": "Date and time",
    "bk.st_session": "Session",
    "bk.st_you": "Details",
    "bk.st_pay": "Confirm",
    "bk.l_court": "Court",
    "bk.l_class": "Class",
    "bk.l_coach": "Coach",
    "bk.l_size": "Group size",
    "bk.l_when": "When",
    "bk.l_dur": "Duration",
    "bk.l_none": "Not chosen yet",
    "bk.mins": "min",
    "bk.spots": "spots left",
    "bk.hall": "Hall",
    "bk.ref": "Reference",
    "court.vb.name": "Volleyball Court",
    "court.vb.hall": "Hall A",
    "court.bb.name": "Basketball Court",
    "court.bb.hall": "Hall A",
    "court.pb.name": "Pickleball Court",
    "court.pb.hall": "Hall B",
    "court.bd.name": "Badminton Court",
    "court.bd.hall": "Hall B",
    "cat.sport.name": "Sport classes",
    "cat.sport.desc": "Volleyball, basketball, pickleball and badminton, grouped by level.",
    "cat.sc.name": "Strength and conditioning",
    "cat.sc.desc": "Group S and C sessions on the strength floor, run by Just Performance.",
    "cat.cert.name": "Certificate courses",
    "cat.cert.desc": "Multi-week courses that end in a certificate.",
    "class.c1.name": "Volleyball, U12 Beginner",
    "class.c1.desc": "Serving, passing and rotation from zero.",
    "class.c2.name": "Badminton, Adult Intermediate",
    "class.c2.desc": "Rotating games for confident players. We sort the sides when you arrive.",
    "class.c3.name": "Strength and conditioning, Adult",
    "class.c3.desc": "Squat, hinge, press and carry. Barbell technique from the floor up.",
    "class.c4.name": "Mobility and recovery, Adult",
    "class.c4.desc": "Sled, bike and carries on the sled lane and turf. The barbell stays racked.",
    "class.c5.name": "Volleyball coaching certificate, Level 1",
    "class.c5.desc": "Six weeks, with an assessment and a certificate at the end.",
    "coach.marco.name": "Head coach",
    "coach.marco.exp": "8 years coaching",
    "coach.marco.tag1": "Volleyball",
    "coach.marco.tag2": "Competition",
    "coach.ken.name": "S&C coach",
    "coach.ken.exp": "10 years, CSCS",
    "coach.ken.tag1": "Strength",
    "coach.ken.tag2": "Return to play",
    "coach.elaine.name": "Beginner coach",
    "coach.elaine.exp": "5 years coaching",
    "coach.elaine.tag1": "Beginner",
    "coach.elaine.tag2": "Pickleball",
    "coach.jojo.name": "Youth coach",
    "coach.jojo.exp": "4 years coaching",
    "coach.jojo.tag1": "Youth",
    "coach.jojo.tag2": "Family",
    "size.1.name": "1 to 1",
    "size.1.desc": "Just you and the coach.",
    "size.2.name": "1 to 2",
    "size.2.desc": "Bring a partner.",
    "size.4.name": "1 to 4",
    "size.4.desc": "Small group, shared rate.",
    "size.8.name": "1 to Team",
    "size.8.desc": "Up to 16 athletes with one coach.",
    "nav.shopTbc": "Store link to confirm",
    "nav.mediaTbc": "Page in the next pass",
    "wa.prefillGeneral": "Hi, I have a question about Sporting Hub Hong Kong.",
    "wa.prefillCorporate": "Hi, I would like a corporate hire quote.",
    "bk.wa_prefill": "Hi, I have a question about a booking.",
    "tweaks.title": "Preview controls",
    "tweaks.viewLabel": "View",
    "tweaks.viewDev": "Dev",
    "tweaks.viewClient": "Client",
    "nav.closeAria": "Close",
    "cat.ws.name": "Workshop",
    "cat.ws.desc": "One-off clinics and short workshops, booked as a single session rather than a series.",
    "class.w1.name": "Serve and spike clinic",
    "class.w1.desc": "Two hours on the jump serve, the approach and the spike. Court shoes needed.",
    "class.w2.name": "Pickleball introduction workshop",
    "class.w2.desc": "Rules, grip and the kitchen line, with paddles provided. No experience needed.",
    "bk.coach_tbc": "name to confirm",
    "bk.filter_all": "All",
    "bk.filter_aria": "Filter coaches by specialty",
    "bk.s8_gcal": "Add to Google Calendar",
    "bk.s8_ics": "Add to Apple Calendar (.ics)",
    "bk.cal_pt": "Personal training",
    "bk.cr_cal": "The Bliss backend renders the confirmation page, so an add to calendar button on it is a change request. Confirm with Edward.",
    "bk.qty_l": "Hours",
    "bk.qty_less": "Fewer hours",
    "bk.qty_more": "More hours",
    "bk.cr_qty": "Hours per booking, max 2 per HKID. The cap cannot be enforced in the front end: the backend has to know what that HKID already booked. Confirm with Edward.",
    "bk.f_hkid": "HKID, first 4 characters",
    "bk.f_hkid_ph": "A123",
    "bk.f_dob": "Date of birth",
    "bk.f_gender": "Gender",
    "bk.g_female": "Female",
    "bk.g_male": "Male",
    "bk.g_other": "Prefer not to say",
    "bk.f_hear": "How did you hear about us?",
    "bk.h_friend": "From a friend",
    "bk.h_social": "Social media",
    "bk.h_search": "Web search",
    "bk.h_walk": "Walked past the venue",
    "bk.h_other": "Somewhere else",
    "bk.f_select": "Please choose",
    "bk.tc_link": "terms and conditions",
    "bk.tc_close": "Close",
    "bk.tc_pending": "Full terms for this category are still to be supplied by the client. This panel shows where they will sit.",
    "bk.tc_h_venue": "Venue booking terms",
    "bk.tc_h_sport": "Sport classes terms",
    "bk.tc_h_sc": "S&C classes terms",
    "bk.tc_h_cert": "Certificate course terms",
    "bk.tc_h_ws": "Workshop terms",
    "bk.tc_h_pt": "Personal training terms",
    "bk.l_term": "Term",
    "bk.l_weekday": "Day",
    "bk.l_lessons": "Lessons",
    "bk.lessons_n": "lessons",
    "bk.s3_day_h": "Which day?",
    "bk.s3_date_h": "Which date?",
    "bk.dow_mon": "Mon",
    "bk.dow_tue": "Tue",
    "bk.dow_wed": "Wed",
    "bk.dow_thu": "Thu",
    "bk.dow_fri": "Fri",
    "bk.dow_sat": "Sat",
    "bk.dow_sun": "Sun",
    "bk.sport_all": "All sports",
    "bk.l_ratio": "Ratio",
    "bk.ratio_team": "Team",
    "bk.ratio_team_d": "Up to 16 athletes with one coach.",
    "bk.l_coaching": "Coaching",
    "bk.l_courtfee": "Court fee",
    "bk.cr_split": "The receipt itemises coaching and court hire as separate lines, charged in one transaction. Confirm with Edward.",
    "bk.cr_eva": "Training class registration should copy EVA's member registration questions exactly (client, 2026-09-24). Nobody has supplied EVA's field list, so this form is unchanged pending it.",
    "court.fb.name": "Floorball Court",
    "court.fb.hall": "Hall A",
    "court.db.name": "Dodgeball Court",
    "court.db.hall": "Hall B",
    "court.tq.name": "Teqvoly Court",
    "court.tq.hall": "Hall B",
    "size.3.name": "1 to 3",
    "size.3.desc": "Three of you, one coach.",
    "sport.vb.name": "Volleyball",
    "sport.bb.name": "Basketball",
    "sport.pb.name": "Pickleball",
    "sport.bd.name": "Badminton",
    "sport.fb.name": "Floorball",
    "sport.db.name": "Dodgeball",
    "sport.tq.name": "Teqvoly",
    "sport.sc.name": "S&C"
  },
  "zh": {
    "nav.home": "主頁",
    "nav.service": "服務",
    "nav.shop": "商店",
    "nav.team": "我們的團隊",
    "nav.corporate": "企業活動",
    "nav.media": "媒體",
    "nav.contact": "聯絡我們",
    "nav.menu_aria": "選單",
    "nav.lang_aria": "語言",
    "cta.book": "預約球場",
    "cta.classes": "查看課程",
    "hero.eyebrow": "2026年11月開幕",
    "hero.lead": "香港室內場地，齊集排球、籃球、匹克球、羽毛球。",
    "pillar.venue": "場地",
    "pillar.venue.desc": "按小時租用球場。排球、籃球、匹克球、羽毛球。",
    "pillar.class": "課程",
    "pillar.class.desc": "運動課程、體能訓練課堂及證書課程。",
    "pillar.pt": "私人教練",
    "pillar.pt.desc": "選擇你的 Just Performance 教練，然後挑選時段。1:1 至 1:8。",
    "pillar.eyebrow": "三種預約方式",
    "pillar.title": "你可以預約的項目",
    "price.from": "由 HK$ TBC 起",
    "intro.eyebrow": "Sporting Hub Hong Kong",
    "intro.title": "一個合適的室內場地，專為香港人真正玩的運動而設。",
    "intro.body1": "兩個場館內設四個球場，一個由 Just Performance 營運的體能訓練區，還有恢復區、更衣室及儲物櫃，以及一間小商店和輕食角落。",
    "intro.body2": "歡迎所有人使用。可按小時預約球場、參加課程，或帶同全公司一起來玩。",
    "intro.link": "查看場地",
    "spaces.eyebrow": "場地",
    "spaces.title": "八個空間，同一個地址。",
    "spaces.volleyball": "排球場",
    "spaces.basketball": "籃球場",
    "spaces.pickleball": "匹克球場",
    "spaces.badminton": "羽毛球場",
    "spaces.sc": "體能訓練區",
    "spaces.lounge": "休息室",
    "spaces.retail": "商店",
    "spaces.recovery": "恢復區",
    "jp.eyebrow": "私人教練",
    "jp.title": "Just Performance，就在場內。",
    "jp.body": "Just Performance 提供體能訓練，設於 Sporting Hub Hong Kong。先選擇教練，再選合適時段。課程人數由1對1至1對團隊（最多16人）。",
    "jp.cta": "選擇教練",
    "jp.groupSize": "1:1 至 1:8",
    "jp.book": "預約",
    "jp.coach1.name": "總教練",
    "jp.coach1.chip1": "力量",
    "jp.coach1.chip2": "體能",
    "jp.coach2.name": "體能教練",
    "jp.coach2.chip1": "活動度",
    "jp.coach2.chip2": "復康",
    "jp.coach3.name": "排球教練",
    "jp.coach3.chip1": "排球",
    "jp.coach3.chip2": "跳躍訓練",
    "jp.tbcBio": "姓名及簡介待確認",
    "corp.eyebrow": "企業活動",
    "corp.title": "團隊活動日、比賽、私人租場。",
    "corp.body": "全個場地或單一球場均可。告訴我們日期及人數，我們會提供報價。",
    "corp.ctaPrimary": "查詢",
    "corp.wa": "WhatsApp 查詢",
    "shop.eyebrow": "商店",
    "shop.title": "鴨舌帽、衞衣、T恤、布袋。",
    "shop.link": "瀏覽商店",
    "shop.tbcName": "商店名稱待確認",
    "band.title": "預約球場",
    "band.sub": "選擇運動項目，然後選擇時段。",
    "band.sport.vb": "排球",
    "band.sport.bb": "籃球",
    "band.sport.pb": "匹克球",
    "band.sport.bd": "羽毛球",
    "band.classes": "課程",
    "band.pt": "私人教練",
    "find.eyebrow": "尋找我們",
    "find.title": "座落香港。地址有待公佈。",
    "find.addressLabel": "地址",
    "find.addressValue": "待確認",
    "find.hoursLabel": "開放時間",
    "find.hoursValue": "待確認",
    "find.mtrLabel": "MTR",
    "find.mtrValue": "待確認",
    "find.waLabel": "WhatsApp",
    "find.waValue": "待確認",
    "find.emailLabel": "電郵",
    "find.emailValue": "待確認",
    "find.waBtn": "WhatsApp 查詢",
    "find.directionsBtn": "查看路線",
    "find.mapCaption": "地圖將於地址確認後嵌入",
    "footer.blurb": "香港室內運動場地。球場、課程、教練及裝備。",
    "footer.bookCol": "預約",
    "footer.venueCol": "場地",
    "footer.companyCol": "公司",
    "footer.linkVenue": "場地",
    "footer.linkClass": "課程",
    "footer.linkPt": "私人教練",
    "footer.linkService": "我們的服務",
    "footer.linkTeam": "我們的團隊",
    "footer.linkCorporate": "企業活動",
    "footer.linkMedia": "媒體",
    "footer.linkShop": "商店",
    "footer.linkContact": "聯絡我們",
    "footer.linkPrivacy": "私隱",
    "footer.bottomName": "Sporting Hub Hong Kong",
    "wa.ariaLabel": "WhatsApp 查詢",
    "wa.tbcNumber": "號碼待確認",
    "bk.wa_aria": "WhatsApp 查詢",
    "bk.back": "返回",
    "bk.next": "下一步",
    "bk.pay": "確認並付款",
    "bk.s1_h": "選擇運動",
    "bk.s1_sub": "先選擇運動，再選所需時長。每個香港身份證最多可預約2小時。",
    "bk.s1c_h": "選擇課程類型",
    "bk.s1c_sub": "運動、體能訓練及證書課程共用一個日曆。",
    "bk.s5_h": "選擇你的教練",
    "bk.s5_sub": "Just Performance 私人教練。選擇教練，然後查看其日曆。",
    "bk.s5b_h": "選擇教練比例",
    "bk.s5b_sub": "教練對學員的比例，每種收費不同。",
    "bk.s3_h": "選擇課堂",
    "bk.s2_h": "選擇日期和時間",
    "bk.s2_note": "每預約1小時選擇1個時段，時段之間不一定要連續。",
    "bk.s6_h": "你的資料",
    "bk.s6_sub": "確認訊息將發送到此。",
    "bk.s6_warn": "請填寫姓名、電郵及電話，並接受免責聲明。",
    "bk.f_first": "名字",
    "bk.f_last": "姓氏",
    "bk.f_email": "電郵",
    "bk.f_phone": "電話",
    "bk.f_notes": "有什麼需要我們知道",
    "bk.f_notes_ph": "傷患、器材、到達時間",
    "bk.c_waiv": "我接受條款及細則，並同意48小時取消政策。",
    "bk.c_mkt": "間中發送課程及活動資訊給我。",
    "bk.s7_h": "核對並確認",
    "bk.s7_sub": "此為原型，無實際收費。",
    "bk.s8_h": "預約成功",
    "bk.s8_sub": "確認電郵已發送至您的郵箱。",
    "bk.s8_home": "返回首頁",
    "bk.s8_again": "預約其他",
    "bk.sum_h": "你的預約",
    "bk.sum_total": "合計",
    "bk.policy": "時段開始前48小時可免費取消。48小時內取消恕不退還。",
    "bk.cr_l": "後台變更請求",
    "bk.cr_cat": "此類別步驟位於標準Bliss流程之前。請與Edward確認可否在不影響其他Bliss客戶的情況下加入。",
    "bk.cr_coach": "Bliss的流程是商店、日期、時間、項目。此處先選教練。請與Edward確認。後備方案：日期優先，並設教練篩選。",
    "bk.cr_pay": "付款沿用現有Bliss的結帳及付款渠道。此處無新增項目。",
    "bk.st_court": "球場",
    "bk.st_cat": "課程類型",
    "bk.st_coach": "教練",
    "bk.st_size": "比例",
    "bk.st_when": "日期及時間",
    "bk.st_session": "時段",
    "bk.st_you": "詳情",
    "bk.st_pay": "確認",
    "bk.l_court": "球場",
    "bk.l_class": "課程",
    "bk.l_coach": "教練",
    "bk.l_size": "人數",
    "bk.l_when": "時間",
    "bk.l_dur": "時長",
    "bk.l_none": "尚未選擇",
    "bk.mins": "分鐘",
    "bk.spots": "剩餘名額",
    "bk.hall": "場館",
    "bk.ref": "參考編號",
    "court.vb.name": "排球場",
    "court.vb.hall": "A場館",
    "court.bb.name": "籃球場",
    "court.bb.hall": "A場館",
    "court.pb.name": "匹克球場",
    "court.pb.hall": "B場館",
    "court.bd.name": "羽毛球場",
    "court.bd.hall": "B場館",
    "cat.sport.name": "運動課程",
    "cat.sport.desc": "排球、籃球、匹克球及羽毛球課程，按程度分組。",
    "cat.sc.name": "體能訓練",
    "cat.sc.desc": "體能訓練場地的小組課程，由 Just Performance 主理。",
    "cat.cert.name": "證書課程",
    "cat.cert.desc": "為期數星期的課程，完成後獲發證書。",
    "class.c1.name": "排球 U12 初班",
    "class.c1.desc": "由零開始學發球、傳球及輪轉。",
    "class.c2.name": "羽毛球 成人中班",
    "class.c2.desc": "為有經驗球手而設的輪換對賽，到場後由我們編排對戰組合。",
    "class.c3.name": "成人體能訓練",
    "class.c3.desc": "深蹲、髖鉸鏈、推舉及負重行走，由基礎學起槓鈴技巧。",
    "class.c4.name": "成人活動恢復",
    "class.c4.desc": "在雪橇跑道及人工草地進行雪橇、單車及負重行走訓練，槓鈴留在架上不用。",
    "class.c5.name": "排球教練證書 L1",
    "class.c5.desc": "為期六星期，完成後設有考核及頒發證書。",
    "coach.marco.name": "總教練",
    "coach.marco.exp": "8年教練經驗",
    "coach.marco.tag1": "排球",
    "coach.marco.tag2": "競賽",
    "coach.ken.name": "體能教練",
    "coach.ken.exp": "10年經驗，CSCS",
    "coach.ken.tag1": "力量",
    "coach.ken.tag2": "重返賽場",
    "coach.elaine.name": "初班教練",
    "coach.elaine.exp": "5年教練經驗",
    "coach.elaine.tag1": "初學者",
    "coach.elaine.tag2": "匹克球",
    "coach.jojo.name": "青年教練",
    "coach.jojo.exp": "4年教練經驗",
    "coach.jojo.tag1": "青年",
    "coach.jojo.tag2": "家庭",
    "size.1.name": "1對1",
    "size.1.desc": "只有你和教練。",
    "size.2.name": "1對2",
    "size.2.desc": "帶個拍檔。",
    "size.4.name": "1對4",
    "size.4.desc": "小組，費用分攤。",
    "size.8.name": "1對團隊",
    "size.8.desc": "最多16位學員，由一位教練指導。",
    "nav.shopTbc": "商店連結待定",
    "nav.mediaTbc": "頁面下階段推出",
    "wa.prefillGeneral": "你好，我有一個關於 Sporting Hub Hong Kong 的問題。",
    "wa.prefillCorporate": "你好，我想索取企業活動租場報價。",
    "bk.wa_prefill": "你好，我想查詢預約的問題。",
    "tweaks.title": "預覽控制",
    "tweaks.viewLabel": "檢視",
    "tweaks.viewDev": "開發",
    "tweaks.viewClient": "客戶",
    "price.fromTemplate": "由 {p} 起",
    "nav.closeAria": "關閉",
    "cat.ws.name": "工作坊",
    "cat.ws.desc": "一次性訓練班及短期工作坊，以單次課程預約，而非系列課程。",
    "class.w1.name": "發球及扣球訓練班",
    "class.w1.desc": "兩小時訓練，涵蓋跳躍發球、助跑及扣球。需穿球場鞋。",
    "class.w2.name": "匹克球入門工作坊",
    "class.w2.desc": "教授規則、握拍方式及廚房線，提供球拍。無需經驗。",
    "bk.coach_tbc": "名稱待確認",
    "bk.filter_all": "全部",
    "bk.filter_aria": "按專長篩選教練",
    "bk.s8_gcal": "加入 Google 日曆",
    "bk.s8_ics": "加入 Apple 日曆 (.ics)",
    "bk.cal_pt": "私人教練",
    "bk.cr_cal": "Bliss 後台會渲染確認頁面，因此在其上添加「加入日曆」按鈕屬於變更請求。請與 Edward 確認。",
    "bk.qty_l": "小時",
    "bk.qty_less": "減少小時",
    "bk.qty_more": "增加小時",
    "bk.cr_qty": "每次預約時數，每個香港身份證最多2小時。前端無法強制執行上限：後端需知道該香港身份證已預約的時數。請與Edward確認。",
    "bk.f_hkid": "身份證號碼，首4位字符",
    "bk.f_hkid_ph": "A123",
    "bk.f_dob": "出生日期",
    "bk.f_gender": "性別",
    "bk.g_female": "女",
    "bk.g_male": "男",
    "bk.g_other": "不願透露",
    "bk.f_hear": "你從哪裡得知我們？",
    "bk.h_friend": "朋友介紹",
    "bk.h_social": "社交媒體",
    "bk.h_search": "網上搜尋",
    "bk.h_walk": "經過場地",
    "bk.h_other": "其他地方",
    "bk.f_select": "請選擇",
    "bk.tc_link": "條款及細則",
    "bk.tc_close": "關閉",
    "bk.tc_pending": "完整條款將於稍後提供。",
    "bk.tc_h_venue": "場地預約條款",
    "bk.tc_h_sport": "運動課程條款",
    "bk.tc_h_sc": "體能訓練課程條款",
    "bk.tc_h_cert": "證書課程條款",
    "bk.tc_h_ws": "工作坊條款",
    "bk.tc_h_pt": "私人教練條款",
    "bk.l_term": "學期",
    "bk.l_weekday": "星期",
    "bk.l_lessons": "堂數",
    "bk.lessons_n": "堂",
    "bk.s3_day_h": "選擇星期",
    "bk.s3_date_h": "選擇日期",
    "bk.dow_mon": "週一",
    "bk.dow_tue": "週二",
    "bk.dow_wed": "週三",
    "bk.dow_thu": "週四",
    "bk.dow_fri": "週五",
    "bk.dow_sat": "週六",
    "bk.dow_sun": "週日",
    "bk.sport_all": "所有運動",
    "bk.l_ratio": "比例",
    "bk.ratio_team": "團隊",
    "bk.ratio_team_d": "最多16位運動員由一位教練指導。",
    "bk.l_coaching": "教練費",
    "bk.l_courtfee": "球場費用",
    "bk.cr_split": "收據會將教練服務及球場租用分項列出，並於同一筆交易收取。請與 Edward 確認。",
    "bk.cr_eva": "訓練課程報名應完全複製 EVA 的會員登記問題（客戶，2026-09-24）。由於未收到 EVA 的欄位清單，此表格維持不變，有待提供。",
    "court.fb.name": "地板球場",
    "court.fb.hall": "場館 A",
    "court.db.name": "躲避球場",
    "court.db.hall": "場館 B",
    "court.tq.name": "Teqvoly 球場",
    "court.tq.hall": "場館 B",
    "size.3.name": "1對3",
    "size.3.desc": "三人同行，一位教練",
    "sport.vb.name": "排球",
    "sport.bb.name": "籃球",
    "sport.pb.name": "匹克球",
    "sport.bd.name": "羽毛球",
    "sport.fb.name": "地板球",
    "sport.db.name": "閃避球",
    "sport.tq.name": "Teqvoly",
    "sport.sc.name": "體能訓練"
  }
};
window.BOOKING_DATA = {
  "STR": {
    "en": {
      "wa_aria": "Ask a question on WhatsApp",
      "back": "Back",
      "next": "Next",
      "pay": "Confirm and pay",
      "s1_h": "Which sport?",
      "s1_sub": "Pick your sport, then how long you need. Maximum 2 hours per HKID.",
      "s1c_h": "What kind of class?",
      "s1c_sub": "Sport, strength and conditioning, and certificates share one calendar.",
      "s5_h": "Choose your coach",
      "s5_sub": "Personal training by Just Performance. Pick the coach, then their calendar.",
      "s5b_h": "Which ratio?",
      "s5b_sub": "Coach to athlete. Each ratio is priced differently.",
      "s3_h": "Pick a session",
      "s2_h": "Pick a date and time",
      "s2_note": "Pick one time slot per hour booked. They do not have to run back to back.",
      "s6_h": "Your details",
      "s6_sub": "We send the confirmation here.",
      "s6_warn": "Fill in your name, email and phone, and accept the waiver.",
      "f_first": "First name",
      "f_last": "Last name",
      "f_email": "Email",
      "f_phone": "Phone",
      "f_notes": "Anything we should know",
      "f_notes_ph": "Injuries, equipment, arrival time",
      "c_waiv": "I accept the terms and conditions and the 48 hour cancellation policy.",
      "c_mkt": "Send me occasional news about classes and events.",
      "s7_h": "Check and confirm",
      "s7_sub": "Nothing is charged in this prototype.",
      "s8_h": "You are booked",
      "s8_sub": "A confirmation is on its way to your email.",
      "s8_home": "Back to home",
      "s8_again": "Book something else",
      "sum_h": "Your booking",
      "sum_total": "Total",
      "policy": "Free cancellation up to 48 hours before the session. Inside 48 hours the booking is non-refundable.",
      "cr_l": "Backend change request",
      "cr_cat": "This category step sits ahead of the standard Bliss flow. Confirm with Edward that it can be added without affecting other Bliss clients.",
      "cr_coach": "Bliss goes store, then date, then time, then item. This picks the coach first. Confirm with Edward. Fallback: date first with a coach filter.",
      "cr_pay": "Payment runs on the existing Bliss checkout and payment channel. Nothing new is built here.",
      "st_court": "Court",
      "st_cat": "Class type",
      "st_coach": "Coach",
      "st_size": "Ratio",
      "st_when": "Date and time",
      "st_session": "Session",
      "st_you": "Details",
      "st_pay": "Confirm",
      "l_court": "Court",
      "l_class": "Class",
      "l_coach": "Coach",
      "l_size": "Group size",
      "l_when": "When",
      "l_dur": "Duration",
      "l_none": "Not chosen yet",
      "mins": "min",
      "spots": "spots left",
      "hall": "Hall",
      "ref": "Reference",
      "wa_prefill": "Hi, I have a question about a booking.",
      "coach_tbc": "name to confirm",
      "filter_all": "All",
      "filter_aria": "Filter coaches by specialty",
      "s8_gcal": "Add to Google Calendar",
      "s8_ics": "Add to Apple Calendar (.ics)",
      "cal_pt": "Personal training",
      "cr_cal": "The Bliss backend renders the confirmation page, so an add to calendar button on it is a change request. Confirm with Edward.",
      "qty_l": "Hours",
      "qty_less": "Fewer hours",
      "qty_more": "More hours",
      "cr_qty": "Hours per booking, max 2 per HKID. The cap cannot be enforced in the front end: the backend has to know what that HKID already booked. Confirm with Edward.",
      "f_hkid": "HKID, first 4 characters",
      "f_hkid_ph": "A123",
      "f_dob": "Date of birth",
      "f_gender": "Gender",
      "g_female": "Female",
      "g_male": "Male",
      "g_other": "Prefer not to say",
      "f_hear": "How did you hear about us?",
      "h_friend": "From a friend",
      "h_social": "Social media",
      "h_search": "Web search",
      "h_walk": "Walked past the venue",
      "h_other": "Somewhere else",
      "f_select": "Please choose",
      "tc_link": "terms and conditions",
      "tc_close": "Close",
      "tc_pending": "Full terms for this category are still to be supplied by the client. This panel shows where they will sit.",
      "tc_h_venue": "Venue booking terms",
      "tc_h_sport": "Sport classes terms",
      "tc_h_sc": "S&C classes terms",
      "tc_h_cert": "Certificate course terms",
      "tc_h_ws": "Workshop terms",
      "tc_h_pt": "Personal training terms",
      "l_term": "Term",
      "l_weekday": "Day",
      "l_lessons": "Lessons",
      "lessons_n": "lessons",
      "s3_day_h": "Which day?",
      "s3_date_h": "Which date?",
      "dow_mon": "Mon",
      "dow_tue": "Tue",
      "dow_wed": "Wed",
      "dow_thu": "Thu",
      "dow_fri": "Fri",
      "dow_sat": "Sat",
      "dow_sun": "Sun",
      "sport_all": "All sports",
      "l_ratio": "Ratio",
      "ratio_team": "Team",
      "ratio_team_d": "Up to 16 athletes with one coach.",
      "l_coaching": "Coaching",
      "l_courtfee": "Court fee",
      "cr_split": "The receipt itemises coaching and court hire as separate lines, charged in one transaction. Confirm with Edward.",
      "cr_eva": "Training class registration should copy EVA's member registration questions exactly (client, 2026-09-24). Nobody has supplied EVA's field list, so this form is unchanged pending it."
    },
    "zh": {
      "wa_aria": "WhatsApp 查詢",
      "back": "返回",
      "next": "下一步",
      "pay": "確認並付款",
      "s1_h": "選擇運動",
      "s1_sub": "先選擇運動，再選所需時長。每個香港身份證最多可預約2小時。",
      "s1c_h": "選擇課程類型",
      "s1c_sub": "運動、體能訓練及證書課程共用一個日曆。",
      "s5_h": "選擇你的教練",
      "s5_sub": "Just Performance 私人教練。選擇教練，然後查看其日曆。",
      "s5b_h": "選擇教練比例",
      "s5b_sub": "教練對學員的比例，每種收費不同。",
      "s3_h": "選擇課堂",
      "s2_h": "選擇日期和時間",
      "s2_note": "每預約1小時選擇1個時段，時段之間不一定要連續。",
      "s6_h": "你的資料",
      "s6_sub": "確認訊息將發送到此。",
      "s6_warn": "請填寫姓名、電郵及電話，並接受免責聲明。",
      "f_first": "名字",
      "f_last": "姓氏",
      "f_email": "電郵",
      "f_phone": "電話",
      "f_notes": "有什麼需要我們知道",
      "f_notes_ph": "傷患、器材、到達時間",
      "c_waiv": "我接受條款及細則，並同意48小時取消政策。",
      "c_mkt": "間中發送課程及活動資訊給我。",
      "s7_h": "核對並確認",
      "s7_sub": "此為原型，無實際收費。",
      "s8_h": "預約成功",
      "s8_sub": "確認電郵已發送至您的郵箱。",
      "s8_home": "返回首頁",
      "s8_again": "預約其他",
      "sum_h": "你的預約",
      "sum_total": "合計",
      "policy": "時段開始前48小時可免費取消。48小時內取消恕不退還。",
      "cr_l": "後台變更請求",
      "cr_cat": "此類別步驟位於標準Bliss流程之前。請與Edward確認可否在不影響其他Bliss客戶的情況下加入。",
      "cr_coach": "Bliss的流程是商店、日期、時間、項目。此處先選教練。請與Edward確認。後備方案：日期優先，並設教練篩選。",
      "cr_pay": "付款沿用現有Bliss的結帳及付款渠道。此處無新增項目。",
      "st_court": "球場",
      "st_cat": "課程類型",
      "st_coach": "教練",
      "st_size": "比例",
      "st_when": "日期及時間",
      "st_session": "時段",
      "st_you": "詳情",
      "st_pay": "確認",
      "l_court": "球場",
      "l_class": "課程",
      "l_coach": "教練",
      "l_size": "人數",
      "l_when": "時間",
      "l_dur": "時長",
      "l_none": "尚未選擇",
      "mins": "分鐘",
      "spots": "剩餘名額",
      "hall": "場館",
      "ref": "參考編號",
      "wa_prefill": "你好，我想查詢預約的問題。",
      "coach_tbc": "名稱待確認",
      "filter_all": "全部",
      "filter_aria": "按專長篩選教練",
      "s8_gcal": "加入 Google 日曆",
      "s8_ics": "加入 Apple 日曆 (.ics)",
      "cal_pt": "私人教練",
      "cr_cal": "Bliss 後台會渲染確認頁面，因此在其上添加「加入日曆」按鈕屬於變更請求。請與 Edward 確認。",
      "qty_l": "小時",
      "qty_less": "減少小時",
      "qty_more": "增加小時",
      "cr_qty": "每次預約時數，每個香港身份證最多2小時。前端無法強制執行上限：後端需知道該香港身份證已預約的時數。請與Edward確認。",
      "f_hkid": "身份證號碼，首4位字符",
      "f_hkid_ph": "A123",
      "f_dob": "出生日期",
      "f_gender": "性別",
      "g_female": "女",
      "g_male": "男",
      "g_other": "不願透露",
      "f_hear": "你從哪裡得知我們？",
      "h_friend": "朋友介紹",
      "h_social": "社交媒體",
      "h_search": "網上搜尋",
      "h_walk": "經過場地",
      "h_other": "其他地方",
      "f_select": "請選擇",
      "tc_link": "條款及細則",
      "tc_close": "關閉",
      "tc_pending": "完整條款將於稍後提供。",
      "tc_h_venue": "場地預約條款",
      "tc_h_sport": "運動課程條款",
      "tc_h_sc": "體能訓練課程條款",
      "tc_h_cert": "證書課程條款",
      "tc_h_ws": "工作坊條款",
      "tc_h_pt": "私人教練條款",
      "l_term": "學期",
      "l_weekday": "星期",
      "l_lessons": "堂數",
      "lessons_n": "堂",
      "s3_day_h": "選擇星期",
      "s3_date_h": "選擇日期",
      "dow_mon": "週一",
      "dow_tue": "週二",
      "dow_wed": "週三",
      "dow_thu": "週四",
      "dow_fri": "週五",
      "dow_sat": "週六",
      "dow_sun": "週日",
      "sport_all": "所有運動",
      "l_ratio": "比例",
      "ratio_team": "團隊",
      "ratio_team_d": "最多16位運動員由一位教練指導。",
      "l_coaching": "教練費",
      "l_courtfee": "球場費用",
      "cr_split": "收據會將教練服務及球場租用分項列出，並於同一筆交易收取。請與 Edward 確認。",
      "cr_eva": "訓練課程報名應完全複製 EVA 的會員登記問題（客戶，2026-09-24）。由於未收到 EVA 的欄位清單，此表格維持不變，有待提供。"
    }
  },
  "COURTS": [
    {
      "id": "vb",
      "dia": "volleyball",
      "en": "Volleyball Court",
      "zh": "排球場",
      "h_en": "Hall A",
      "h_zh": "A場館"
    },
    {
      "id": "bb",
      "dia": "basketball",
      "en": "Basketball Court",
      "zh": "籃球場",
      "h_en": "Hall A",
      "h_zh": "A場館"
    },
    {
      "id": "pb",
      "dia": "pickleball",
      "en": "Pickleball Court",
      "zh": "匹克球場",
      "h_en": "Hall B",
      "h_zh": "B場館"
    },
    {
      "id": "bd",
      "dia": "badminton",
      "en": "Badminton Court",
      "zh": "羽毛球場",
      "h_en": "Hall B",
      "h_zh": "B場館"
    },
    {
      "id": "fb",
      "dia": null,
      "en": "Floorball Court",
      "zh": "地板球場",
      "h_en": "Hall A",
      "h_zh": "場館 A"
    },
    {
      "id": "db",
      "dia": null,
      "en": "Dodgeball Court",
      "zh": "躲避球場",
      "h_en": "Hall B",
      "h_zh": "場館 B"
    },
    {
      "id": "tq",
      "dia": null,
      "en": "Teqvoly Court",
      "zh": "Teqvoly 球場",
      "h_en": "Hall B",
      "h_zh": "場館 B"
    }
  ],
  "CATS": [
    {
      "id": "sport",
      "kind": "term",
      "en": "Sport classes",
      "zh": "運動課程",
      "d_en": "Volleyball, basketball, pickleball and badminton, grouped by level.",
      "d_zh": "排球、籃球、匹克球及羽毛球課程，按程度分組。"
    },
    {
      "id": "sc",
      "kind": "term",
      "en": "Strength and conditioning",
      "zh": "體能訓練",
      "d_en": "Group S and C sessions on the strength floor, run by Just Performance.",
      "d_zh": "體能訓練場地的小組課程，由 Just Performance 主理。"
    },
    {
      "id": "cert",
      "kind": "event",
      "en": "Certificate courses",
      "zh": "證書課程",
      "d_en": "Multi-week courses that end in a certificate.",
      "d_zh": "為期數星期的課程，完成後獲發證書。"
    },
    {
      "id": "ws",
      "kind": "event",
      "en": "Workshop",
      "zh": "工作坊",
      "d_en": "One-off clinics and short workshops, booked as a single session rather than a series.",
      "d_zh": "一次性訓練班及短期工作坊，以單次課程預約，而非系列課程。"
    }
  ],
  "CLASSES": [
    {
      "id": "c1",
      "cat": "sport",
      "en": "Volleyball, U12 Beginner",
      "zh": "排球 U12 初班",
      "coach": "Head coach",
      "dur": 90,
      "spots": 8,
      "d_en": "Serving, passing and rotation from zero.",
      "d_zh": "由零開始學發球、傳球及輪轉。",
      "sport": "vb",
      "start": "09:00",
      "weekday": 2,
      "term": "Nov-Dec",
      "lessons": 8
    },
    {
      "id": "c2",
      "cat": "sport",
      "en": "Badminton, Adult Intermediate",
      "zh": "羽毛球 成人中班",
      "coach": "Beginner coach",
      "dur": 90,
      "spots": 3,
      "d_en": "Rotating games for confident players. We sort the sides when you arrive.",
      "d_zh": "為有經驗球手而設的輪換對賽，到場後由我們編排對戰組合。",
      "sport": "bd",
      "start": "18:00",
      "weekday": 4,
      "term": "Nov-Dec",
      "lessons": 8
    },
    {
      "id": "c3",
      "cat": "sc",
      "en": "Strength and conditioning, Adult",
      "zh": "成人體能訓練",
      "coach": "S&C coach",
      "dur": 60,
      "spots": 6,
      "d_en": "Squat, hinge, press and carry. Barbell technique from the floor up.",
      "d_zh": "深蹲、髖鉸鏈、推舉及負重行走，由基礎學起槓鈴技巧。",
      "sport": null,
      "start": "07:00",
      "weekday": 1,
      "term": "Nov-Dec",
      "lessons": 12
    },
    {
      "id": "c4",
      "cat": "sc",
      "en": "Mobility and recovery, Adult",
      "zh": "成人活動恢復",
      "coach": "S&C coach",
      "dur": 45,
      "spots": 10,
      "d_en": "Sled, bike and carries on the sled lane and turf. The barbell stays racked.",
      "d_zh": "在雪橇跑道及人工草地進行雪橇、單車及負重行走訓練，槓鈴留在架上不用。",
      "sport": null,
      "start": "10:00",
      "weekday": 6,
      "term": "Nov-Dec",
      "lessons": 12
    },
    {
      "id": "c5",
      "cat": "cert",
      "en": "Volleyball coaching certificate, Level 1",
      "zh": "排球教練證書 L1",
      "coach": "Head coach",
      "dur": 480,
      "spots": 4,
      "d_en": "Six weeks, with an assessment and a certificate at the end.",
      "d_zh": "為期六星期，完成後設有考核及頒發證書。",
      "sport": null,
      "start": "09:00",
      "date": "2026-11-14",
      "end": "17:00"
    },
    {
      "id": "w1",
      "cat": "ws",
      "en": "Serve and spike clinic",
      "zh": "發球及扣球訓練班",
      "coach": "Head coach",
      "dur": 120,
      "spots": 12,
      "d_en": "Two hours on the jump serve, the approach and the spike. Court shoes needed.",
      "d_zh": "兩小時訓練，涵蓋跳躍發球、助跑及扣球。需穿球場鞋。",
      "sport": "vb",
      "start": "19:00",
      "date": "2026-11-21",
      "end": "21:00"
    },
    {
      "id": "w2",
      "cat": "ws",
      "en": "Pickleball introduction workshop",
      "zh": "匹克球入門工作坊",
      "coach": "Beginner coach",
      "dur": 90,
      "spots": 16,
      "d_en": "Rules, grip and the kitchen line, with paddles provided. No experience needed.",
      "d_zh": "教授規則、握拍方式及廚房線，提供球拍。無需經驗。",
      "sport": "pb",
      "start": "19:30",
      "date": "2026-11-28",
      "end": "21:00"
    }
  ],
  "COACHES": [
    {
      "id": "marco",
      "sport": "vb",
      "n": "Head coach",
      "en": "Volleyball · Competition",
      "zh": "排球 · 競賽",
      "x_en": "8 years coaching",
      "x_zh": "8年教練經驗",
      "tags_en": [
        "Volleyball",
        "Competition"
      ],
      "tags_zh": [
        "排球",
        "競賽"
      ]
    },
    {
      "id": "ken",
      "sport": "sc",
      "n": "S&C coach",
      "en": "Strength · Return to play",
      "zh": "力量 · 重返賽場",
      "x_en": "10 years, CSCS",
      "x_zh": "10年經驗，CSCS",
      "tags_en": [
        "Strength",
        "Return to play"
      ],
      "tags_zh": [
        "力量",
        "重返賽場"
      ]
    },
    {
      "id": "elaine",
      "sport": "pb",
      "n": "Beginner coach",
      "en": "Beginner · Pickleball",
      "zh": "初學者 · 匹克球",
      "x_en": "5 years coaching",
      "x_zh": "5年教練經驗",
      "tags_en": [
        "Beginner",
        "Pickleball"
      ],
      "tags_zh": [
        "初學者",
        "匹克球"
      ]
    },
    {
      "id": "jojo",
      "sport": "bd",
      "n": "Youth coach",
      "en": "Youth · Family",
      "zh": "青年 · 家庭",
      "x_en": "4 years coaching",
      "x_zh": "4年教練經驗",
      "tags_en": [
        "Youth",
        "Family"
      ],
      "tags_zh": [
        "青年",
        "家庭"
      ]
    }
  ],
  "SIZES": [
    {
      "id": "1",
      "en": "1 to 1",
      "zh": "1對1",
      "d_en": "Just you and the coach.",
      "d_zh": "只有你和教練。"
    },
    {
      "id": "2",
      "en": "1 to 2",
      "zh": "1對2",
      "d_en": "Bring a partner.",
      "d_zh": "帶個拍檔。"
    },
    {
      "id": "3",
      "en": "1 to 3",
      "zh": "1對3",
      "d_en": "Three of you, one coach.",
      "d_zh": "三人同行，一位教練"
    },
    {
      "id": "4",
      "en": "1 to 4",
      "zh": "1對4",
      "d_en": "Small group, shared rate.",
      "d_zh": "小組，費用分攤。"
    },
    {
      "id": "8",
      "en": "1 to Team",
      "zh": "1對團隊",
      "d_en": "Up to 16 athletes with one coach.",
      "d_zh": "最多16位學員，由一位教練指導。"
    }
  ],
  "SPORTS": {
    "vb": {
      "en": "Volleyball",
      "zh": "排球"
    },
    "bb": {
      "en": "Basketball",
      "zh": "籃球"
    },
    "pb": {
      "en": "Pickleball",
      "zh": "匹克球"
    },
    "bd": {
      "en": "Badminton",
      "zh": "羽毛球"
    },
    "fb": {
      "en": "Floorball",
      "zh": "地板球"
    },
    "db": {
      "en": "Dodgeball",
      "zh": "閃避球"
    },
    "tq": {
      "en": "Teqvoly",
      "zh": "Teqvoly"
    },
    "sc": {
      "en": "S&C",
      "zh": "體能訓練"
    }
  }
};
