/* GENERATED FILE. Do not hand-edit.
 * Produced by scripts/build_strings.py from strings.en.json + strings.zh.json.
 * Rerun build_strings.py (after zh_copy.py for any new keys) to regenerate. */
window.STRINGS = {
  "en": {
    "nav.home": "Home",
    "nav.service": "Our Service",
    "nav.shop": "Shop",
    "nav.team": "Our Team",
    "nav.corporate": "Corporate Event",
    "nav.media": "Media",
    "nav.contact": "Contact Us",
    "nav.menu_aria": "Menu",
    "nav.lang_aria": "Language",
    "cta.book": "Book a court",
    "cta.classes": "See classes",
    "hero.eyebrow": "Opening November 2026",
    "hero.lead": "Volleyball, basketball, pickleball, badminton. One roof, Hong Kong.",
    "pillar.venue": "Venue",
    "pillar.venue.desc": "Courts by the hour. Volleyball, basketball, pickleball, badminton.",
    "pillar.class": "Class",
    "pillar.class.desc": "Sport classes, S&C sessions and certificate courses.",
    "pillar.pt": "Personal training",
    "pillar.pt.desc": "Pick your Just Performance coach, then pick a time. 1:1 to 1:8.",
    "pillar.eyebrow": "Three ways to book",
    "pillar.title": "What you can book",
    "price.from": "from HK$ TBC",
    "price.fromTemplate": "from {p}",
    "intro.eyebrow": "Sporting Hub Hong Kong",
    "intro.title": "A proper indoor venue, built for the sports Hong Kong actually plays.",
    "intro.body1": "Four courts across two halls, a strength and conditioning floor run by Just Performance, a recovery zone, changing rooms and lockers, and a small shop and supper corner.",
    "intro.body2": "Open to everyone. Book by the hour, join a class, or bring the whole office.",
    "intro.link": "See the venue",
    "spaces.eyebrow": "The venue",
    "spaces.title": "Eight spaces, one address.",
    "spaces.volleyball": "Volleyball court",
    "spaces.basketball": "Basketball court",
    "spaces.pickleball": "Pickleball court",
    "spaces.badminton": "Badminton court",
    "spaces.sc": "Strength and conditioning floor",
    "spaces.lounge": "Lounge",
    "spaces.retail": "Shop",
    "spaces.recovery": "Recovery zone",
    "jp.eyebrow": "Personal training",
    "jp.title": "Just Performance, in the building.",
    "jp.body": "Strength and conditioning by Just Performance by Hong Kong Ling Hub. Choose your coach first, then a time that suits you. Sessions run 1:1 to 1:8.",
    "jp.cta": "Choose a coach",
    "jp.groupSize": "1:1 to 1:8",
    "jp.book": "Book",
    "jp.coach1.name": "Head coach",
    "jp.coach1.chip1": "Strength",
    "jp.coach1.chip2": "Conditioning",
    "jp.coach2.name": "S&C coach",
    "jp.coach2.chip1": "Mobility",
    "jp.coach2.chip2": "Rehab",
    "jp.coach3.name": "Volleyball coach",
    "jp.coach3.chip1": "Volleyball",
    "jp.coach3.chip2": "Jump training",
    "jp.tbcBio": "Name and bio to confirm",
    "corp.eyebrow": "Corporate events",
    "corp.title": "Team days, tournaments, private hire.",
    "corp.body": "The whole venue or a single court. Tell us the date and headcount and we will come back with a quote.",
    "corp.ctaPrimary": "Enquire",
    "corp.wa": "WhatsApp",
    "shop.eyebrow": "Shop",
    "shop.title": "Caps, hoodies, tees, totes.",
    "shop.link": "Visit the shop",
    "shop.tbcName": "Store name to confirm",
    "band.title": "Book a court",
    "band.sub": "Pick the sport, then the hour.",
    "band.sport.vb": "Volleyball",
    "band.sport.bb": "Basketball",
    "band.sport.pb": "Pickleball",
    "band.sport.bd": "Badminton",
    "band.classes": "Classes",
    "band.pt": "Personal training",
    "find.eyebrow": "Find us",
    "find.title": "In Hong Kong. Address to follow.",
    "find.addressLabel": "Address",
    "find.addressValue": "To confirm",
    "find.hoursLabel": "Opening hours",
    "find.hoursValue": "To confirm",
    "find.mtrLabel": "MTR",
    "find.mtrValue": "To confirm",
    "find.waLabel": "WhatsApp",
    "find.waValue": "To confirm",
    "find.emailLabel": "Email",
    "find.emailValue": "To confirm",
    "find.waBtn": "WhatsApp us",
    "find.directionsBtn": "Get directions",
    "find.mapCaption": "Map embeds once the address is confirmed",
    "footer.blurb": "An indoor sports venue in Hong Kong. Courts, classes, coaching and kit.",
    "footer.bookCol": "Book",
    "footer.venueCol": "Venue",
    "footer.companyCol": "Company",
    "footer.linkVenue": "Venue",
    "footer.linkClass": "Class",
    "footer.linkPt": "Personal training",
    "footer.linkService": "Our Service",
    "footer.linkTeam": "Our Team",
    "footer.linkCorporate": "Corporate Event",
    "footer.linkMedia": "Media",
    "footer.linkShop": "Shop",
    "footer.linkContact": "Contact Us",
    "footer.linkPrivacy": "Privacy",
    "footer.bottomName": "Sporting Hub Hong Kong",
    "wa.ariaLabel": "Message us on WhatsApp",
    "wa.tbcNumber": "Number to confirm",
    "bk.wa_aria": "Ask a question on WhatsApp",
    "bk.back": "Back",
    "bk.next": "Next",
    "bk.pay": "Confirm and pay",
    "bk.s1_h": "Which court?",
    "bk.s1_sub": "Four courts across two halls. Rent by the hour.",
    "bk.s1c_h": "What kind of class?",
    "bk.s1c_sub": "Sport, strength and conditioning, and certificates share one calendar.",
    "bk.s5_h": "Choose your coach",
    "bk.s5_sub": "Personal training by Just Performance. Pick the coach, then their calendar.",
    "bk.s5b_h": "How many of you?",
    "bk.s5b_sub": "Group size changes the rate per person.",
    "bk.s3_h": "Pick a session",
    "bk.s2_h": "Pick a date and time",
    "bk.s2_note": "Courts book by the hour. Struck-through times are taken.",
    "bk.s6_h": "Your details",
    "bk.s6_sub": "We send the confirmation here.",
    "bk.s6_warn": "Fill in your name, email and phone, and accept the waiver.",
    "bk.f_first": "First name",
    "bk.f_last": "Last name",
    "bk.f_email": "Email",
    "bk.f_phone": "Phone",
    "bk.f_notes": "Anything we should know",
    "bk.f_notes_ph": "Injuries, equipment, arrival time",
    "bk.c_waiv": "I accept the venue waiver and the 48 hour cancellation policy.",
    "bk.c_mkt": "Send me occasional news about classes and events.",
    "bk.s7_h": "Check and confirm",
    "bk.s7_sub": "Nothing is charged in this prototype.",
    "bk.s8_h": "You are booked",
    "bk.s8_sub": "A confirmation is on its way to your email.",
    "bk.s8_home": "Back to home",
    "bk.s8_again": "Book something else",
    "bk.sum_h": "Your booking",
    "bk.sum_total": "Total",
    "bk.policy": "Free cancellation up to 48 hours before the session. Inside 48 hours the booking is non-refundable.",
    "bk.cr_l": "Backend change request",
    "bk.cr_cat": "This category step sits ahead of the standard Bliss flow. Confirm with Edward that it can be added without affecting other Bliss clients.",
    "bk.cr_coach": "Bliss goes store, then date, then time, then item. This picks the coach first. Confirm with Edward. Fallback: date first with a coach filter.",
    "bk.cr_pay": "Payment runs on the existing Bliss checkout and payment channel. Nothing new is built here.",
    "bk.st_court": "Court",
    "bk.st_cat": "Class type",
    "bk.st_coach": "Coach",
    "bk.st_size": "Group",
    "bk.st_when": "Date and time",
    "bk.st_session": "Session",
    "bk.st_you": "Details",
    "bk.st_pay": "Confirm",
    "bk.l_court": "Court",
    "bk.l_class": "Class",
    "bk.l_coach": "Coach",
    "bk.l_size": "Group size",
    "bk.l_when": "When",
    "bk.l_dur": "Duration",
    "bk.l_none": "Not chosen yet",
    "bk.mins": "min",
    "bk.spots": "spots left",
    "bk.hall": "Hall",
    "bk.ref": "Reference",
    "court.vb.name": "Court 1 · Volleyball",
    "court.vb.hall": "Hall A",
    "court.bb.name": "Court 2 · Basketball",
    "court.bb.hall": "Hall A",
    "court.pb.name": "Court 3 · Pickleball",
    "court.pb.hall": "Hall B",
    "court.bd.name": "Court 4 · Badminton",
    "court.bd.hall": "Hall B",
    "cat.sport.name": "Sport classes",
    "cat.sport.desc": "Volleyball, basketball, pickleball and badminton, grouped by level.",
    "cat.sc.name": "Strength and conditioning",
    "cat.sc.desc": "Group S and C sessions on the strength floor, run by Just Performance.",
    "cat.cert.name": "Certificate courses",
    "cat.cert.desc": "Multi-week courses that end in a certificate.",
    "class.c1.name": "Volleyball, beginner",
    "class.c1.desc": "Serving, passing and rotation from zero.",
    "class.c2.name": "Open rally night",
    "class.c2.desc": "Rotating games for confident players. We sort the sides when you arrive.",
    "class.c3.name": "Strength foundations",
    "class.c3.desc": "Squat, hinge, press and carry. Barbell technique from the floor up.",
    "class.c4.name": "Conditioning circuit",
    "class.c4.desc": "Sled, bike and carries on the sled lane and turf. The barbell stays racked.",
    "class.c5.name": "Level 1 coaching certificate",
    "class.c5.desc": "Six weeks, with an assessment and a certificate at the end.",
    "coach.marco.name": "Head coach",
    "coach.marco.exp": "8 years coaching",
    "coach.marco.tag1": "Volleyball",
    "coach.marco.tag2": "Competition",
    "coach.ken.name": "S&C coach",
    "coach.ken.exp": "10 years, CSCS",
    "coach.ken.tag1": "Strength",
    "coach.ken.tag2": "Return to play",
    "coach.elaine.name": "Beginner coach",
    "coach.elaine.exp": "5 years coaching",
    "coach.elaine.tag1": "Beginner",
    "coach.elaine.tag2": "Pickleball",
    "coach.jojo.name": "Youth coach",
    "coach.jojo.exp": "4 years coaching",
    "coach.jojo.tag1": "Youth",
    "coach.jojo.tag2": "Family",
    "size.1.name": "1 to 1",
    "size.1.desc": "Just you and the coach.",
    "size.2.name": "1 to 2",
    "size.2.desc": "Bring a partner.",
    "size.4.name": "1 to 4",
    "size.4.desc": "Small group, shared rate.",
    "size.8.name": "1 to 8",
    "size.8.desc": "Team or full squad.",
    "nav.shopTbc": "Store link to confirm",
    "nav.mediaTbc": "Page in the next pass",
    "wa.prefillGeneral": "Hi, I have a question about Sporting Hub Hong Kong.",
    "wa.prefillCorporate": "Hi, I would like a corporate hire quote.",
    "bk.wa_prefill": "Hi, I have a question about a booking.",
    "tweaks.title": "Preview controls",
    "tweaks.viewLabel": "View",
    "tweaks.viewDev": "Dev",
    "tweaks.viewClient": "Client",
    "nav.closeAria": "Close"
  },
  "zh": {
    "nav.home": "主頁",
    "nav.service": "服務",
    "nav.shop": "商店",
    "nav.team": "我們的團隊",
    "nav.corporate": "企業活動",
    "nav.media": "媒體",
    "nav.contact": "聯絡我們",
    "nav.menu_aria": "選單",
    "nav.lang_aria": "語言",
    "cta.book": "預約球場",
    "cta.classes": "查看課程",
    "hero.eyebrow": "2026年11月開幕",
    "hero.lead": "香港室內場地，齊集排球、籃球、匹克球、羽毛球。",
    "pillar.venue": "場地",
    "pillar.venue.desc": "按小時租用球場。排球、籃球、匹克球、羽毛球。",
    "pillar.class": "課程",
    "pillar.class.desc": "運動課程、體能訓練課堂及證書課程。",
    "pillar.pt": "私人教練",
    "pillar.pt.desc": "選擇你的 Just Performance 教練，然後挑選時段。1:1 至 1:8。",
    "pillar.eyebrow": "三種預約方式",
    "pillar.title": "你可以預約的項目",
    "price.from": "由 HK$ TBC 起",
    "intro.eyebrow": "Sporting Hub Hong Kong",
    "intro.title": "一個合適的室內場地，專為香港人真正玩的運動而設。",
    "intro.body1": "兩個場館內設四個球場，一個由 Just Performance 營運的體能訓練區，還有恢復區、更衣室及儲物櫃，以及一間小商店和輕食角落。",
    "intro.body2": "歡迎所有人使用。可按小時預約球場、參加課程，或帶同全公司一起來玩。",
    "intro.link": "查看場地",
    "spaces.eyebrow": "場地",
    "spaces.title": "八個空間，同一個地址。",
    "spaces.volleyball": "排球場",
    "spaces.basketball": "籃球場",
    "spaces.pickleball": "匹克球場",
    "spaces.badminton": "羽毛球場",
    "spaces.sc": "體能訓練區",
    "spaces.lounge": "休息室",
    "spaces.retail": "商店",
    "spaces.recovery": "恢復區",
    "jp.eyebrow": "私人教練",
    "jp.title": "Just Performance，就在場內。",
    "jp.body": "由 Hong Kong Ling Hub 呈獻的 Just Performance 體能訓練。先選擇教練，再揀選適合你的時段。課堂人數由 1:1 至 1:8。",
    "jp.cta": "選擇教練",
    "jp.groupSize": "1:1 至 1:8",
    "jp.book": "預約",
    "jp.coach1.name": "總教練",
    "jp.coach1.chip1": "力量",
    "jp.coach1.chip2": "體能",
    "jp.coach2.name": "體能教練",
    "jp.coach2.chip1": "活動度",
    "jp.coach2.chip2": "復康",
    "jp.coach3.name": "排球教練",
    "jp.coach3.chip1": "排球",
    "jp.coach3.chip2": "跳躍訓練",
    "jp.tbcBio": "姓名及簡介待確認",
    "corp.eyebrow": "企業活動",
    "corp.title": "團隊活動日、比賽、私人租場。",
    "corp.body": "全個場地或單一球場均可。告訴我們日期及人數，我們會提供報價。",
    "corp.ctaPrimary": "查詢",
    "corp.wa": "WhatsApp 查詢",
    "shop.eyebrow": "商店",
    "shop.title": "鴨舌帽、衞衣、T恤、布袋。",
    "shop.link": "瀏覽商店",
    "shop.tbcName": "商店名稱待確認",
    "band.title": "預約球場",
    "band.sub": "選擇運動項目，然後選擇時段。",
    "band.sport.vb": "排球",
    "band.sport.bb": "籃球",
    "band.sport.pb": "匹克球",
    "band.sport.bd": "羽毛球",
    "band.classes": "課程",
    "band.pt": "私人教練",
    "find.eyebrow": "尋找我們",
    "find.title": "座落香港。地址有待公佈。",
    "find.addressLabel": "地址",
    "find.addressValue": "待確認",
    "find.hoursLabel": "開放時間",
    "find.hoursValue": "待確認",
    "find.mtrLabel": "MTR",
    "find.mtrValue": "待確認",
    "find.waLabel": "WhatsApp",
    "find.waValue": "待確認",
    "find.emailLabel": "電郵",
    "find.emailValue": "待確認",
    "find.waBtn": "WhatsApp 查詢",
    "find.directionsBtn": "查看路線",
    "find.mapCaption": "地圖將於地址確認後嵌入",
    "footer.blurb": "香港室內運動場地。球場、課程、教練及裝備。",
    "footer.bookCol": "預約",
    "footer.venueCol": "場地",
    "footer.companyCol": "公司",
    "footer.linkVenue": "場地",
    "footer.linkClass": "課程",
    "footer.linkPt": "私人教練",
    "footer.linkService": "我們的服務",
    "footer.linkTeam": "我們的團隊",
    "footer.linkCorporate": "企業活動",
    "footer.linkMedia": "媒體",
    "footer.linkShop": "商店",
    "footer.linkContact": "聯絡我們",
    "footer.linkPrivacy": "私隱",
    "footer.bottomName": "Sporting Hub Hong Kong",
    "wa.ariaLabel": "WhatsApp 查詢",
    "wa.tbcNumber": "號碼待確認",
    "bk.wa_aria": "WhatsApp 查詢",
    "bk.back": "返回",
    "bk.next": "下一步",
    "bk.pay": "確認並付款",
    "bk.s1_h": "選擇球場？",
    "bk.s1_sub": "兩個場館共四個球場。按小時租用。",
    "bk.s1c_h": "邊種課程？",
    "bk.s1c_sub": "運動、體能訓練及證書課程共用一個日曆。",
    "bk.s5_h": "選擇你的教練",
    "bk.s5_sub": "Just Performance 私人教練。選擇教練，然後查看其日曆。",
    "bk.s5b_h": "人數",
    "bk.s5b_sub": "人數會影響每位收費。",
    "bk.s3_h": "選擇課堂",
    "bk.s2_h": "選擇日期和時間",
    "bk.s2_note": "球場按小時預約。已劃線時段代表已被預訂。",
    "bk.s6_h": "你的資料",
    "bk.s6_sub": "確認訊息將發送到此。",
    "bk.s6_warn": "請填寫姓名、電郵及電話，並接受免責聲明。",
    "bk.f_first": "名字",
    "bk.f_last": "姓氏",
    "bk.f_email": "電郵",
    "bk.f_phone": "電話",
    "bk.f_notes": "備註",
    "bk.f_notes_ph": "傷患、器材、到達時間",
    "bk.c_waiv": "我接受場地免責聲明及48小時取消政策。",
    "bk.c_mkt": "間中發送課程及活動資訊給我。",
    "bk.s7_h": "核對並確認",
    "bk.s7_sub": "此為原型，無實際收費。",
    "bk.s8_h": "預約成功",
    "bk.s8_sub": "確認電郵已發送至您的郵箱。",
    "bk.s8_home": "返回首頁",
    "bk.s8_again": "預約其他",
    "bk.sum_h": "你的預約",
    "bk.sum_total": "合計",
    "bk.policy": "時段開始前48小時可免費取消。48小時內取消恕不退還。",
    "bk.cr_l": "後台變更請求",
    "bk.cr_cat": "此類別步驟位於標準Bliss流程之前。請與Edward確認可否在不影響其他Bliss客戶的情況下加入。",
    "bk.cr_coach": "Bliss的流程是商店、日期、時間、項目。此處先選教練。請與Edward確認。後備方案：日期優先，並設教練篩選。",
    "bk.cr_pay": "付款沿用現有Bliss的結帳及付款渠道。此處無新增項目。",
    "bk.st_court": "球場",
    "bk.st_cat": "課程類型",
    "bk.st_coach": "教練",
    "bk.st_size": "人數",
    "bk.st_when": "日期及時間",
    "bk.st_session": "時段",
    "bk.st_you": "詳情",
    "bk.st_pay": "確認",
    "bk.l_court": "球場",
    "bk.l_class": "課程",
    "bk.l_coach": "教練",
    "bk.l_size": "人數",
    "bk.l_when": "時間",
    "bk.l_dur": "時長",
    "bk.l_none": "尚未選擇",
    "bk.mins": "分鐘",
    "bk.spots": "剩餘名額",
    "bk.hall": "場館",
    "bk.ref": "參考編號",
    "court.vb.name": "1號場 · 排球",
    "court.vb.hall": "A場館",
    "court.bb.name": "2號場 · 籃球",
    "court.bb.hall": "A場館",
    "court.pb.name": "3號場 · 匹克球",
    "court.pb.hall": "B場館",
    "court.bd.name": "4號場 · 羽毛球",
    "court.bd.hall": "B場館",
    "cat.sport.name": "運動課程",
    "cat.sport.desc": "排球、籃球、匹克球及羽毛球課程，按程度分組。",
    "cat.sc.name": "體能訓練",
    "cat.sc.desc": "體能訓練場地的小組課程，由 Just Performance 主理。",
    "cat.cert.name": "證書課程",
    "cat.cert.desc": "為期數星期的課程，完成後獲發證書。",
    "class.c1.name": "排球初班",
    "class.c1.desc": "由零開始學發球、傳球及輪轉。",
    "class.c2.name": "公開對打夜",
    "class.c2.desc": "為有經驗球手而設的輪換對賽，到場後由我們編排對戰組合。",
    "class.c3.name": "力量基礎",
    "class.c3.desc": "深蹲、髖鉸鏈、推舉及負重行走，由基礎學起槓鈴技巧。",
    "class.c4.name": "體能循環",
    "class.c4.desc": "在雪橇跑道及人工草地進行雪橇、單車及負重行走訓練，槓鈴留在架上不用。",
    "class.c5.name": "一級教練證書",
    "class.c5.desc": "為期六星期，完成後設有考核及頒發證書。",
    "coach.marco.name": "總教練",
    "coach.marco.exp": "8年教練經驗",
    "coach.marco.tag1": "排球",
    "coach.marco.tag2": "競賽",
    "coach.ken.name": "體能教練",
    "coach.ken.exp": "10年經驗，CSCS",
    "coach.ken.tag1": "力量",
    "coach.ken.tag2": "重返賽場",
    "coach.elaine.name": "初班教練",
    "coach.elaine.exp": "5年教練經驗",
    "coach.elaine.tag1": "初學者",
    "coach.elaine.tag2": "匹克球",
    "coach.jojo.name": "青年教練",
    "coach.jojo.exp": "4年教練經驗",
    "coach.jojo.tag1": "青年",
    "coach.jojo.tag2": "家庭",
    "size.1.name": "1對1",
    "size.1.desc": "只有你和教練。",
    "size.2.name": "1對2",
    "size.2.desc": "帶個拍檔。",
    "size.4.name": "1對4",
    "size.4.desc": "小組，費用分攤。",
    "size.8.name": "1對8",
    "size.8.desc": "團隊或全隊。",
    "nav.shopTbc": "商店連結待定",
    "nav.mediaTbc": "頁面下階段推出",
    "wa.prefillGeneral": "你好，我有一個關於 Sporting Hub Hong Kong 的問題。",
    "wa.prefillCorporate": "你好，我想索取企業活動租場報價。",
    "bk.wa_prefill": "你好，我想查詢關於預約嘅問題。",
    "tweaks.title": "預覽控制",
    "tweaks.viewLabel": "檢視",
    "tweaks.viewDev": "開發",
    "tweaks.viewClient": "客戶",
    "price.fromTemplate": "由 {p} 起",
    "nav.closeAria": "關閉"
  }
};
window.BOOKING_DATA = {
  "STR": {
    "en": {
      "wa_aria": "Ask a question on WhatsApp",
      "back": "Back",
      "next": "Next",
      "pay": "Confirm and pay",
      "s1_h": "Which court?",
      "s1_sub": "Four courts across two halls. Rent by the hour.",
      "s1c_h": "What kind of class?",
      "s1c_sub": "Sport, strength and conditioning, and certificates share one calendar.",
      "s5_h": "Choose your coach",
      "s5_sub": "Personal training by Just Performance. Pick the coach, then their calendar.",
      "s5b_h": "How many of you?",
      "s5b_sub": "Group size changes the rate per person.",
      "s3_h": "Pick a session",
      "s2_h": "Pick a date and time",
      "s2_note": "Courts book by the hour. Struck-through times are taken.",
      "s6_h": "Your details",
      "s6_sub": "We send the confirmation here.",
      "s6_warn": "Fill in your name, email and phone, and accept the waiver.",
      "f_first": "First name",
      "f_last": "Last name",
      "f_email": "Email",
      "f_phone": "Phone",
      "f_notes": "Anything we should know",
      "f_notes_ph": "Injuries, equipment, arrival time",
      "c_waiv": "I accept the venue waiver and the 48 hour cancellation policy.",
      "c_mkt": "Send me occasional news about classes and events.",
      "s7_h": "Check and confirm",
      "s7_sub": "Nothing is charged in this prototype.",
      "s8_h": "You are booked",
      "s8_sub": "A confirmation is on its way to your email.",
      "s8_home": "Back to home",
      "s8_again": "Book something else",
      "sum_h": "Your booking",
      "sum_total": "Total",
      "policy": "Free cancellation up to 48 hours before the session. Inside 48 hours the booking is non-refundable.",
      "cr_l": "Backend change request",
      "cr_cat": "This category step sits ahead of the standard Bliss flow. Confirm with Edward that it can be added without affecting other Bliss clients.",
      "cr_coach": "Bliss goes store, then date, then time, then item. This picks the coach first. Confirm with Edward. Fallback: date first with a coach filter.",
      "cr_pay": "Payment runs on the existing Bliss checkout and payment channel. Nothing new is built here.",
      "st_court": "Court",
      "st_cat": "Class type",
      "st_coach": "Coach",
      "st_size": "Group",
      "st_when": "Date and time",
      "st_session": "Session",
      "st_you": "Details",
      "st_pay": "Confirm",
      "l_court": "Court",
      "l_class": "Class",
      "l_coach": "Coach",
      "l_size": "Group size",
      "l_when": "When",
      "l_dur": "Duration",
      "l_none": "Not chosen yet",
      "mins": "min",
      "spots": "spots left",
      "hall": "Hall",
      "ref": "Reference",
      "wa_prefill": "Hi, I have a question about a booking."
    },
    "zh": {
      "wa_aria": "WhatsApp 查詢",
      "back": "返回",
      "next": "下一步",
      "pay": "確認並付款",
      "s1_h": "選擇球場？",
      "s1_sub": "兩個場館共四個球場。按小時租用。",
      "s1c_h": "邊種課程？",
      "s1c_sub": "運動、體能訓練及證書課程共用一個日曆。",
      "s5_h": "選擇你的教練",
      "s5_sub": "Just Performance 私人教練。選擇教練，然後查看其日曆。",
      "s5b_h": "人數",
      "s5b_sub": "人數會影響每位收費。",
      "s3_h": "選擇課堂",
      "s2_h": "選擇日期和時間",
      "s2_note": "球場按小時預約。已劃線時段代表已被預訂。",
      "s6_h": "你的資料",
      "s6_sub": "確認訊息將發送到此。",
      "s6_warn": "請填寫姓名、電郵及電話，並接受免責聲明。",
      "f_first": "名字",
      "f_last": "姓氏",
      "f_email": "電郵",
      "f_phone": "電話",
      "f_notes": "備註",
      "f_notes_ph": "傷患、器材、到達時間",
      "c_waiv": "我接受場地免責聲明及48小時取消政策。",
      "c_mkt": "間中發送課程及活動資訊給我。",
      "s7_h": "核對並確認",
      "s7_sub": "此為原型，無實際收費。",
      "s8_h": "預約成功",
      "s8_sub": "確認電郵已發送至您的郵箱。",
      "s8_home": "返回首頁",
      "s8_again": "預約其他",
      "sum_h": "你的預約",
      "sum_total": "合計",
      "policy": "時段開始前48小時可免費取消。48小時內取消恕不退還。",
      "cr_l": "後台變更請求",
      "cr_cat": "此類別步驟位於標準Bliss流程之前。請與Edward確認可否在不影響其他Bliss客戶的情況下加入。",
      "cr_coach": "Bliss的流程是商店、日期、時間、項目。此處先選教練。請與Edward確認。後備方案：日期優先，並設教練篩選。",
      "cr_pay": "付款沿用現有Bliss的結帳及付款渠道。此處無新增項目。",
      "st_court": "球場",
      "st_cat": "課程類型",
      "st_coach": "教練",
      "st_size": "人數",
      "st_when": "日期及時間",
      "st_session": "時段",
      "st_you": "詳情",
      "st_pay": "確認",
      "l_court": "球場",
      "l_class": "課程",
      "l_coach": "教練",
      "l_size": "人數",
      "l_when": "時間",
      "l_dur": "時長",
      "l_none": "尚未選擇",
      "mins": "分鐘",
      "spots": "剩餘名額",
      "hall": "場館",
      "ref": "參考編號",
      "wa_prefill": "你好，我想查詢關於預約嘅問題。"
    }
  },
  "COURTS": [
    {
      "id": "vb",
      "dia": "volleyball",
      "en": "Court 1 · Volleyball",
      "zh": "1號場 · 排球",
      "h_en": "Hall A",
      "h_zh": "A場館"
    },
    {
      "id": "bb",
      "dia": "basketball",
      "en": "Court 2 · Basketball",
      "zh": "2號場 · 籃球",
      "h_en": "Hall A",
      "h_zh": "A場館"
    },
    {
      "id": "pb",
      "dia": "pickleball",
      "en": "Court 3 · Pickleball",
      "zh": "3號場 · 匹克球",
      "h_en": "Hall B",
      "h_zh": "B場館"
    },
    {
      "id": "bd",
      "dia": "badminton",
      "en": "Court 4 · Badminton",
      "zh": "4號場 · 羽毛球",
      "h_en": "Hall B",
      "h_zh": "B場館"
    }
  ],
  "CATS": [
    {
      "id": "sport",
      "en": "Sport classes",
      "zh": "運動課程",
      "d_en": "Volleyball, basketball, pickleball and badminton, grouped by level.",
      "d_zh": "排球、籃球、匹克球及羽毛球課程，按程度分組。"
    },
    {
      "id": "sc",
      "en": "Strength and conditioning",
      "zh": "體能訓練",
      "d_en": "Group S and C sessions on the strength floor, run by Just Performance.",
      "d_zh": "體能訓練場地的小組課程，由 Just Performance 主理。"
    },
    {
      "id": "cert",
      "en": "Certificate courses",
      "zh": "證書課程",
      "d_en": "Multi-week courses that end in a certificate.",
      "d_zh": "為期數星期的課程，完成後獲發證書。"
    }
  ],
  "CLASSES": [
    {
      "id": "c1",
      "cat": "sport",
      "en": "Volleyball, beginner",
      "zh": "排球初班",
      "coach": "Head coach",
      "dur": 60,
      "spots": 8,
      "d_en": "Serving, passing and rotation from zero.",
      "d_zh": "由零開始學發球、傳球及輪轉。"
    },
    {
      "id": "c2",
      "cat": "sport",
      "en": "Open rally night",
      "zh": "公開對打夜",
      "coach": "Beginner coach",
      "dur": 90,
      "spots": 3,
      "d_en": "Rotating games for confident players. We sort the sides when you arrive.",
      "d_zh": "為有經驗球手而設的輪換對賽，到場後由我們編排對戰組合。"
    },
    {
      "id": "c3",
      "cat": "sc",
      "en": "Strength foundations",
      "zh": "力量基礎",
      "coach": "S&C coach",
      "dur": 60,
      "spots": 6,
      "d_en": "Squat, hinge, press and carry. Barbell technique from the floor up.",
      "d_zh": "深蹲、髖鉸鏈、推舉及負重行走，由基礎學起槓鈴技巧。"
    },
    {
      "id": "c4",
      "cat": "sc",
      "en": "Conditioning circuit",
      "zh": "體能循環",
      "coach": "S&C coach",
      "dur": 45,
      "spots": 10,
      "d_en": "Sled, bike and carries on the sled lane and turf. The barbell stays racked.",
      "d_zh": "在雪橇跑道及人工草地進行雪橇、單車及負重行走訓練，槓鈴留在架上不用。"
    },
    {
      "id": "c5",
      "cat": "cert",
      "en": "Level 1 coaching certificate",
      "zh": "一級教練證書",
      "coach": "Head coach",
      "dur": 120,
      "spots": 4,
      "d_en": "Six weeks, with an assessment and a certificate at the end.",
      "d_zh": "為期六星期，完成後設有考核及頒發證書。"
    }
  ],
  "COACHES": [
    {
      "id": "marco",
      "n": "Head coach",
      "en": "Volleyball · Competition",
      "zh": "排球 · 競賽",
      "x_en": "8 years coaching",
      "x_zh": "8年教練經驗",
      "tags_en": [
        "Volleyball",
        "Competition"
      ],
      "tags_zh": [
        "排球",
        "競賽"
      ]
    },
    {
      "id": "ken",
      "n": "S&C coach",
      "en": "Strength · Return to play",
      "zh": "力量 · 重返賽場",
      "x_en": "10 years, CSCS",
      "x_zh": "10年經驗，CSCS",
      "tags_en": [
        "Strength",
        "Return to play"
      ],
      "tags_zh": [
        "力量",
        "重返賽場"
      ]
    },
    {
      "id": "elaine",
      "n": "Beginner coach",
      "en": "Beginner · Pickleball",
      "zh": "初學者 · 匹克球",
      "x_en": "5 years coaching",
      "x_zh": "5年教練經驗",
      "tags_en": [
        "Beginner",
        "Pickleball"
      ],
      "tags_zh": [
        "初學者",
        "匹克球"
      ]
    },
    {
      "id": "jojo",
      "n": "Youth coach",
      "en": "Youth · Family",
      "zh": "青年 · 家庭",
      "x_en": "4 years coaching",
      "x_zh": "4年教練經驗",
      "tags_en": [
        "Youth",
        "Family"
      ],
      "tags_zh": [
        "青年",
        "家庭"
      ]
    }
  ],
  "SIZES": [
    {
      "id": "1",
      "en": "1 to 1",
      "zh": "1對1",
      "d_en": "Just you and the coach.",
      "d_zh": "只有你和教練。"
    },
    {
      "id": "2",
      "en": "1 to 2",
      "zh": "1對2",
      "d_en": "Bring a partner.",
      "d_zh": "帶個拍檔。"
    },
    {
      "id": "4",
      "en": "1 to 4",
      "zh": "1對4",
      "d_en": "Small group, shared rate.",
      "d_zh": "小組，費用分攤。"
    },
    {
      "id": "8",
      "en": "1 to 8",
      "zh": "1對8",
      "d_en": "Team or full squad.",
      "d_zh": "團隊或全隊。"
    }
  ]
};
